// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI93-1IH4UM-xxlUFms8Nt2cE1Bqk-HWE',
    appId: '1:368506088840:web:37667a0bef30dcbd6d5e3d',
    messagingSenderId: '368506088840',
    projectId: 'authorization-5955e',
    authDomain: 'authorization-5955e.firebaseapp.com',
    storageBucket: 'authorization-5955e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAunjBEuuaHTHIkL5Gd0FL2PDDehjPgXk8',
    appId: '1:368506088840:android:9f402e416a64c2b86d5e3d',
    messagingSenderId: '368506088840',
    projectId: 'authorization-5955e',
    storageBucket: 'authorization-5955e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBneIYKpzsfMu5qUjypCLK_kXSifWRDR3Y',
    appId: '1:368506088840:ios:b1c61ea1e3bf56526d5e3d',
    messagingSenderId: '368506088840',
    projectId: 'authorization-5955e',
    storageBucket: 'authorization-5955e.appspot.com',
    iosBundleId: 'com.example.bookingNewHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBneIYKpzsfMu5qUjypCLK_kXSifWRDR3Y',
    appId: '1:368506088840:ios:e08a7862b3b4ded46d5e3d',
    messagingSenderId: '368506088840',
    projectId: 'authorization-5955e',
    storageBucket: 'authorization-5955e.appspot.com',
    iosBundleId: 'com.example.bookingNewHotel.RunnerTests',
  );
}
